### ISSUE TITLE
Not a issue, but and advice

### ISSUE THREAD

**Issue by erm3nda** [datasets/edgar#1]
Sec.gov will shutdown it's FTP on dec '16, so every module based on fp() would have to download data through https instead.

**Comment by rufuspollock** [comment]
@erm3nda thanks - super useful heads up ;-)

**Comment by tuangeek** [comment]
Thanks erm3nda. I was trying some of the ftp stuff and I was getting frustrated that it wasn't working. Eventually I saw on their website that they turned off FTP.

**Comment by erm3nda** [comment]
> Eventually I saw on their website that they turned off FTP

I saw that notification on the website before come here to advice it. I saw that many examples around internet built around egdar website where built on top of the ftp service so i thought it will be really helpful for newcomers to don't get so much frustrated :-)

yw.

**Comment by rufuspollock** [comment]
@erm3nda @tuangeek if either of you could do a pull request to give the new http links that would be super useful 😄

**Comment by erm3nda** [comment]
ftp://ftp.sec.gov/edgar/full-index/{YYYY}/QTR{1-4}/{index-name}.[gz|zip] is now https://www.sec.gov/Archives/edgar/full-index/{YYYY}/QTR{1-4}/{index-name}.[gz|zip].

**Comment by rufuspollock** [comment]
FIXED by @tuangeek in https://github.com/datasets/edgar/pull/3
